version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'Australia/Sydney'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    groups:
      docker:
        patterns:
          - '*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'Australia/Sydney'
    groups:
      github:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/ui'
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'Australia/Sydney'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    groups:
      npm:
        patterns:
          - '*'

  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'Australia/Sydney'
    groups:
      go:
        patterns:
          - '*'
