[default]
locale = "en-au"

[default.extend-identifiers]
center = "center"
optimize = "optimize"
optimized = "optimized"
optimizeLegibility = "optimizeLegibility"
Authorization = "Authorization"
Organization = "Organization"

[files]
ignore-vcs = true
extend-exclude = [
  "vendor",
  ".git",
  "go.mod",
  "go.sum",
  "LICENSE.md",
  "PRIVACY.md",
]
